title: LxTechnologies Status Page
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://lx-technologies-status.netlify.app/
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: API
      description: How we connect our bot to other services.
      category: LX Technologies Shards
    - name: Database
      category: LX Technologies Shards
      description: Where all data on servers, users, and levels/leaderboards are held,
        alongside other data.
    - name: Root Services
      category: LX Technologies Shards
      description: This is where all the basic services are held, such as startup,
        main commands. ETC.
    - name: "Online Server Control "
      category: LX Technologies Shards
      description: Where you can control your servers bot through a online panel.
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#e74a4c"
  enableLastMod: true
  headerTextColor: white
  logo: /img/bot_version.png
  incidentPostsPerPage: 3
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: LX Technologies Shards
      untitled: false
      description: ""
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
